import type { Metadata } from "next";
import localFont from "next/font/local";
import NavBar from '../components/NavBar'; // Import NavBar component
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Main content of the page */}
        {children}
        
        {/* Bottom Navigation */}
        <NavBar /> {/* The NavBar will always be visible at the bottom */}
      </body>
    </html>
  );
}
